%%% TODO migrate tex code to cls

% \NeedsTeXFormat{LaTeX2e}
% \ProvidesClass{cv}[2020/12/10 custom cv class]
% \RequirePackage{titlesec}
% \LoadClass{article}

% \titleformat{\section}
% 	{\Large\scshape\raggedright}  	% set large, small cap, left align
% 	{}{0em}
% 	\vspace{}
% 	% {}
% 	% [\titlerule]					% horizontal line after heading
% \titleformat{\subsection}
% {\raggedright}  	% set large, small cap, left align
% {}{0em}
% {}
